name: workflow ascii art

on: push

jobs:
  ascii_workflow:
    runs-on: ubuntu-latest

    steps:
          
      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Generate ASCII artwork
        run: cowsay -f dragon "Run for cover, I am a dragon...RAWR"