name: workflow ascii art

on: push

jobs:
  ascii_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate ASCII
        run: bash .github/workflows/ascii.sh